export const Users =[
    {
        "id": 1,
        "first_name": "John",
        "last_name": "Travolta",
        "email": "j.t@gmail.com",
        "gender": "male",
    },
    {
        "id": 2,
        "first_name": "Jim",
        "last_name": "Jarmoosh",
        "email": "j.j@gmail.com",
        "gender": "male",
    },
    {
        "id": 3,
        "first_name": "Jack",
        "last_name": "Daniels",
        "email": "j.d@gmail.com",
        "gender": "male",
    },
    {
        "id": 4,
        "first_name": "Albert",
        "last_name": "Davis",
        "email": "a.d@gmail.com",
        "gender": "male",
    },
    {
        "id": 5,
        "first_name": "Nick",
        "last_name": "Anderson",
        "email": "n.a@gmail.com",
        "gender": "male",
    },
    {
        "id": 6,
        "first_name": "Sam",
        "last_name": "Kent",
        "email": "s.k@gmail.com",
        "gender": "male",
    },
    {
        "id": 7,
        "first_name": "Tim",
        "last_name": "Tansarian",
        "email": "t.t@gmail.com",
        "gender": "male",
    },
    {
        "id": 8,
        "first_name": "Edward",
        "last_name": "Anstein",
        "email": "e.a@gmail.com",
        "gender": "male",
    },
    {
        "id": 9,
        "first_name": "Elisabeth",
        "last_name": "Tellor",
        "email": "e.t@gmail.com",
        "gender": "female",
    },
    {
        "id": 10,
        "first_name": "Cate",
        "last_name": "Richards",
        "email": "c.r@gmail.com",
        "gender": "female",
    },
    {
        "id": 11,
        "first_name": "Simon",
        "last_name": "Servinto",
        "email": "s.s@gmail.com",
        "gender": "male",
    },
    {
        "id": 12,
        "first_name": "Adam",
        "last_name": "Smith",
        "email": "a.s@gmail.com",
        "gender": "male",
    },
    {
        "id": 13,
        "first_name": "Kent",
        "last_name": "Tortiallo",
        "email": "k.t@gmail.com",
        "gender": "male",
    },
    {
        "id": 14,
        "first_name": "Pedro",
        "last_name": "Marvello",
        "email": "p.m@gmail.com",
        "gender": "male",
    },
    {
        "id": 15,
        "first_name": "Anna",
        "last_name": "Sting",
        "email": "a.s@gmail.com",
        "gender": "female",
    },
    {
        "id": 16,
        "first_name": "Sara",
        "last_name": "Jackson",
        "email": "s.j@gmail.com",
        "gender": "female",
    },
    {
        "id": 17,
        "first_name": "Nora",
        "last_name": "Jones",
        "email": "n.j@gmail.com",
        "gender": "female",
    },
]